# -*- coding: utf-8 -*-
"""ANN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-1-ikfDJPZtEGxrneM-3dotJFej-Aw2

Global AI HUB Build an artificial neural network
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, minmax_scale
from sklearn.model_selection import train_test_split

data=pd.read_excel("date_fruit.xlsx")

data.head()

data["Class"].unique()

x=data.drop("Class",axis=1)
y=data.loc[:,"Class"]

x_scaled= minmax_scale(x)
x=pd.DataFrame(x_scaled)

x.head()

encoder=LabelEncoder()
y=encoder.fit_transform(y)

x_train,x_temp,y_train,y_temp=train_test_split(x,y,train_size=0.8)
x_val,x_test,y_val,y_test=train_test_split(x_temp,y_temp,train_size=0.5)

import tensorflow as tf

model=tf.keras.Sequential()

input_layer=tf.keras.layers.Dense(4096, input_shape=(34,),activation="relu")

model.add(input_layer)

#hidden layer 1
model.add(tf.keras.layers.Dense(4096,activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
#hidden layer 2
model.add(tf.keras.layers.Dense(4096,activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
#hidden layer 3
model.add(tf.keras.layers.Dense(4096,activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
#hidden layer 4
model.add(tf.keras.layers.Dense(4096,activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))

model.add(tf.keras.layers.Dense(7,activation="softmax"))

model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

results=model.fit(x_train,y_train, epochs=20, validation_data=(x_val,y_val))

test_result=model.test_on_batch(x_test,y_test)

test_result

